services:
  db:
    image: postgres:latest
    container_name: soccer-scores-postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SoccerScoresLocal
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: soccer-scores-redis-cache
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  pgdata:
  redis:
    driver: local
